model_config:
  visual_bert:
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: pretraining
    num_labels: 2
    visual_target: null
    task_matched: true
    task_visn: false
    use_image_position_embedding: true
    itm_filtering: false
    itm_filtering_start_epoch: 2
    # freeze_base: false
    # losses:
    # - type: cross_entropy
dataset_config:
  itm_conceptual_captions:
    data_dir: ${env.data_dir}/datasets
    return_features_info: true
    false_caption: true
    two_sentence: false
    features:
      train:
      - flickr30k/defaults/features/vinvl_detectron.lmdb
      val:
      - flickr30k/defaults/features/vinvl_detectron.lmdb
      test:
      - flickr30k/defaults/features/vinvl_detectron.lmdb
    annotations:
      train:
      - flickr30k/defaults/annotations/flickr30k_itm_train.jsonl
      val:
      - flickr30k/defaults/annotations/flickr30k_itm_val.jsonl
      test:
      #- flickr30k/defaults/annotations/flickr30k_itm_test_final.jsonl
      - flickr30k/defaults/annotations/flickr30k_itm_minitest.jsonl
    max_features: 100
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 60
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height
     # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false


optimizer:
  type: adam_w
  params:
    lr: 5e-4
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 13000
    num_training_steps: 130000

evaluation:
  metrics:
  - accuracy

training:
  # batch_size: 480
  batch_size: 128
  lr_scheduler: true
  clip_gradients: true
  max_grad_l2_norm: 2.0
  # Don't forget to update schedule_attributes if you update this
  find_unused_parameters: true
  max_updates: 130000
  # early_stop:
  #   criteria: itm_flickr30k/accuracy
  #   minimize: false

checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
