includes:
- ./defaults.yaml

model_config:
  visual_bert:
    use_image_position_embedding: true

dataset_config:
  vqa2:
    use_images: false
    use_features: true
    features:
      train:
      - coco/defaults/features/trainval2014_vinvl_nopadding.lmdb
      - coco/defaults/features/trainval2014_vinvl_nopadding.lmdb
      val:
      - coco/defaults/features/trainval2014_vinvl_nopadding.lmdb
      test:
      - coco/defaults/features/test2015_vinvl_nopadding.lmdb
    annotations:
      train:
      - vqa2/defaults/annotations/imdb_train2014.npy
      # - vqa2/defaults/annotations/imdb_val2014.npy
      - vqa2/defaults/annotations/imdb_valminusminival2014.npy
      val:
      - vqa2/defaults/annotations/imdb_minival2014.npy
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 30
      transformer_bbox_processor:
          type: transformer_bbox
          params:
            bbox_key: bbox
            image_width_key: image_width
            image_height_key: image_height
    return_features_info: true
    max_features: 100

training:
  tensorboard: true
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 28000

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2800
    num_training_steps: 28000
