model_config:
  vilbert:
    training_head_type: pretraining
    visual_target: 2

dataset_config:
  masked_conceptual_captions:
    return_features_info: true
    use_image_feature_masks: false
    features:
      train:
      - cc/defaults/features/cc_val.lmdb
      val:
      - cc/defaults/features/cc_val.lmdb
      test:
      - cc/defaults/features/cc_val.lmdb
    annotations:
      train:
      - cc/defaults/annotations/val.npy
      val:
      - cc/defaults/annotations/val.npy
      test:
      - cc/defaults/annotations/val.npy


optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 1000
    num_training_steps: 11000

training:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 11000
  find_unused_parameters: true
