includes:
- configs/models/mmf_transformer/pretrain.yaml
- ./pytext_defaults.yaml


model_config:
  mmf_transformer:
    heads:
      - type: mlm
        vocab_size: 250002
    modalities:
    - type: text
      key: post_text
      segment_id: 0
    - type: image
      key: image
      embedding_dim: 256
      position_dim: 1
      segment_id: 1

dataset_config:
  hive:
    processors:
      batch_processor:
        type: features_with_text
        params:
          processors:
            text_processor:
              type: multi_sentence_spm_tokenizer
              params:
                tokenizer_config:
                  type: pytext_spm
                  params:
                    model_path: manifold://nlp_technologies/tree/xlm/models/xlm_r/model
                    vocab_path: manifold://nlp_technologies/tree/xlm/models/xlm_r/vocab
                    max_vocab: 250002
                    do_lower_case: true
                mask_probability: 0.15
                max_seq_length: 512
                fusion: stack
