includes:
- ./defaults.yaml

dataset_config:
  vqa2:
    use_images: false
    use_features: true
    features:
      train:
      - coco/defaults/features/trainval2014_vinvl_nopadding.lmdb
      - coco/defaults/features/trainval2014_vinvl_nopadding.lmdb
      val:
      - coco/defaults/features/trainval2014_vinvl_nopadding.lmdb
      test:
      - coco/defaults/features/test2015_vinvl_nopadding.lmdb
    annotations:
      train:
      - vqa2/defaults/annotations/imdb_train2014.npy
      - vqa2/defaults/annotations/imdb_val2014.npy
      val:
      - vqa2/defaults/annotations/imdb_val2014.npy
      test:
      - vqa2/defaults/annotations/imdb_test2015.npy
    return_features_info: true
    max_features: 100
