includes:
- ./defaults.yaml
- configs/fb/models/mmf_transformer/pytext.yaml

model_config:
  mmf_transformer:
    modalities:
    - type: text
      key: ocr
      segment_id: -1
      position_dim: 128
    - type: image
      key: xray
      embedding_dim: 256
      position_dim: 1
      segment_id: -1
    image_encoder:
      type: identity
      params:
        in_dim: 256

dataset_config:
  hive:
    processors:
      batch_processor:
        type: features_with_text
        params:
          processors:
            text_processor:
              type: multi_sentence_spm_tokenizer
              params:
                tokenizer_config:
                  type: pytext_spm
                  params:
                    model_path: manifold://nlp_technologies/tree/xlm/models/xlm_r/model
                    vocab_path: manifold://nlp_technologies/tree/xlm/models/xlm_r/vocab
                    max_vocab: 250002
                    do_lower_case: true
                mask_probability: 0
                max_seq_length: 128
                fusion: null
