model_config:
  visual_bert:
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: refcoco
    num_labels: 100
    use_image_position_embedding: true
    freeze_base: false
    losses:
    - type: cross_entropy

dataset_config:
  refcoco:
    return_features_info: true
    features:
      train:
      - /data/zmykevin/fb_intern/data/mmf_data/datasets/refcoco/defaults/features/trainval2014_vinvl_nopadding.lmdb
      val:
      - /data/zmykevin/fb_intern/data/mmf_data/datasets/refcoco/defaults/features/trainval2014_vinvl_nopadding.lmdb
      test:
      - /data/zmykevin/fb_intern/data/mmf_data/datasets/refcoco/defaults/features/trainval2014_vinvl_nopadding.lmdb
    annotations:
      train:
      - /data/zmykevin/fb_intern/data/mmf_data/datasets/refcoco/defaults/annotations/refcoco_plus_train.jsonl
      val:
      - /data/zmykevin/fb_intern/data/mmf_data/datasets/refcoco/defaults/annotations/refcoco_plus_dev.jsonl
      test:
      - /data/zmykevin/fb_intern/data/mmf_data/datasets/refcoco/defaults/annotations/refcoco_plus_testA.jsonl
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 60
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height


optimizer:
  type: adam_w
  params:
    lr: 2e-4
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: 20000

evaluation:
  metrics:
  - refcoco_accuracy

training:
  # batch_size: 480
  batch_size: 256
  lr_scheduler: true
  clip_gradients: true
  max_grad_l2_norm: 2.0
  tensorboard: true
  # Don't forget to update schedule_attributes if you update this
  find_unused_parameters: true
  max_updates: 20000
  early_stop:
    criteria: refcoco/refcoco_accuracy
    minimize: false

checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
