includes:
- configs/models/mmbt/classification.yaml
- configs/models/mmbt/with_features.yaml
# Please see fbcode/faim/mmf/mmf/datasets/fb/builders/hive/builder.py
# for details on configuration
dataset_config:
  hive:
    constructor:
      namespace: feed
      table: misinfo_onboxdataloader_test
      partitions: null
    set_name_key: set_name
    set_name_mapping:
      train: training
      val: validation
      test: testing
    schema:
    - content_id
    - xray_hash
    - post_text
    - ocr_text
    - is_misinfo
    - set_name
    filters: []
    processors:
      batch_processor:
        type: features_with_text
        params:
          feature_key: xray_hash
          text_keys:
          - post_text
          - ocr_text
          label_key: is_misinfo
          id_key: content_id
          processors:
            text_processor:
              type: multi_sentence_bert_tokenizer
              params:
                tokenizer_config:
                  type: bert-base-uncased
                  params:
                    do_lower_case: true
                mask_probability: 0
                max_seq_length: 128
                fusion: concat
            feature_processor:
              type: xray_hash
              params: {}


model_config:
  mmbt:
    direct_features_input: true
    modal_encoder:
      type: identity
      params: {}
    modal_hidden_size: 256


scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

evaluation:
    metrics:
    - binary_ap
    - roc_auc

training:
  batch_size: 32
  lr_scheduler: true
  max_updates: 22000
  early_stop:
    criteria: hive/binary_ap
    minimize: false
