includes:
- ./defaults.yaml

model_config:
  visual_bert:
    visual_target: null
    task_matched: true
    task_visn: true
    task_mrtm: true
    visual_losses:
    - obj
    - feat
    use_image_position_embedding: true
    itm_filtering: true
    itm_filtering_start_epoch: 2

dataset_config:
  masked_conceptual_captions_image_phrase:
      return_features_info: true
      false_caption: false
      two_sentence: false
      use_image_feature_masks: true
      mrtm_enabled: true
      features:
        train:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_4.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_5.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_10.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_11.lmdb
        val:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        test:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      annotations:
        train:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_0.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_1.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_2.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_3.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_4.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_5.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_6.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_7.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_8.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_9.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_10.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_11.npy
        val:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/val_vinvl_itm_fixed.npy
        test:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/val_vinvl_itm_fixed.npy
      processors:
        masked_token_processor:
          type: masked_token
          params:
            tokenizer_config:
              type: bert-base-uncased
              params:
                do_lower_case: true
            mask_probability: 0.15
            max_seq_length: 60
        masked_region_processor:
          type: masked_region_OMVM
          params:
            tokenizer_config:
              type: bert-base-uncased
              params:
                do_lower_case: true
            mask_probability: 0.15
            mask_region_probability: 0.9
  masked_conceptual_captions_image_tag:
      return_features_info: true
      false_caption: false
      two_sentence: false
      features:
        train:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_4.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_5.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_10.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_11.lmdb
        val:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        test:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      annotations:
        train:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_0.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_1.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_2.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_3.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_4.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_5.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_6.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_7.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_8.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_9.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_10.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_11.npy
        val:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/val_vinvl_itm_fixed.npy
        test:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/val_vinvl_itm_fixed.npy
      processors:
        masked_token_processor:
          type: masked_token_image_tag
          params:
            tokenizer_config:
              type: bert-base-uncased
              params:
                do_lower_case: true
            mask_probability: 0.15
            max_seq_length: 60
        masked_region_processor:
          type: masked_region
          params:
            mask_probability: 0.15
            mask_region_probability: 0.9
  itm_conceptual_captions:
    return_features_info: true
    false_caption: true
    two_sentence: false
    features:
        train:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_4.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_5.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_10.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_11.lmdb
        val:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        test:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      annotations:
        train:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_0.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_1.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_2.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_3.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_4.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_5.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_6.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_7.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_8.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_9.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_10.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_11.npy
        val:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/val_vinvl_itm_fixed.npy
        test:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/val_vinvl_itm_fixed.npy
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 60
  masked_conceptual_captions:
    return_features_info: true
    false_caption: false
    two_sentence: false
    use_image_feature_masks: true
    features:
      features:
        train:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_4.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_5.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_10.lmdb
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_train_11.lmdb
        val:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        test:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      annotations:
        train:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_0.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_1.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_2.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_3.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_4.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_5.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_6.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_7.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_8.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_9.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_10.npy
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/train_cc_11.npy
        val:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/val_vinvl_itm_fixed.npy
        test:
        - /data/zmykevin/fb_intern/data/mmf_data/datasets/cc/defaults/annotations/val_vinvl_itm_fixed.npy
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 60
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.9


optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 13000
    num_training_steps: 130000

training:
  batch_size: 480
  lr_scheduler: true
  max_updates: 130000
  find_unused_parameters: true
  tensorboard: true
  fp16: true
  clip_gradients: true
  max_grad_l2_norm: 5.0
  epoch_aware: true
  checkpoint_interval: 5000
  evaluation_internal: 5000

evaluation:
  metrics:
  - accuracy
