includes:
- ./defaults.yaml

model_config:
  visual_bert:
    visual_target: null
    task_matched: true
    task_visn: true
    use_image_position_embedding: true
    itm_filtering: true
    itm_filtering_start_epoch: 2

dataset_config:
  masked_conceptual_captions_image_tag:
      return_features_info: true
      false_caption: false
      two_sentence: false
      features:
        train:
        - cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
        # train:
        # - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        val:
        - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        test:
        - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      annotations:
        train:
        - cc/defaults/annotations/train_vinvl_ucla_tags_0.npy
        - cc/defaults/annotations/train_vinvl_ucla_tags_1.npy
        - cc/defaults/annotations/train_vinvl_ucla_tags_2.npy
        - cc/defaults/annotations/train_vinvl_ucla_tags_3.npy
        - cc/defaults/annotations/train_vinvl_ucla_tags_6.npy
        - cc/defaults/annotations/train_vinvl_ucla_tags_7.npy
        - cc/defaults/annotations/train_vinvl_ucla_tags_8.npy
        - cc/defaults/annotations/train_vinvl_ucla_tags_9.npy
        # train:
        # - cc/defaults/annotations/val_vinvl_ucla_tags.npy
        val:
        - cc/defaults/annotations/val_vinvl_itm.npy
        test:
        - cc/defaults/annotations/val_vinvl_itm.npy

      processors:
        masked_token_processor:
          type: masked_token_image_tag
          params:
            tokenizer_config:
              type: bert-base-uncased
              params:
                do_lower_case: true
            mask_probability: 0.15
            max_seq_length: 60
        masked_region_processor:
          type: masked_region
          params:
            mask_probability: 0.15
            mask_region_probability: 0.9
  itm_conceptual_captions:
    return_features_info: true
    false_caption: true
    two_sentence: false
    features:
      train:
      - cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
      # train:
      # - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      val:
      - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      test:
      - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
    annotations:
      train:
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_0.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_1.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_2.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_3.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_6.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_7.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_8.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_9.npy
      # train:
      # - cc/defaults/annotations/val_vinvl_itm.npy
      val:
      - cc/defaults/annotations/val_vinvl_itm.npy
      test:
      - cc/defaults/annotations/val_vinvl_itm.npy
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 60

  masked_conceptual_captions:
    return_features_info: true
    false_caption: false
    two_sentence: false
    use_image_feature_masks: false
    features:
      train:
      - cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
      # - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      val:
      - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      test:
      - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
    annotations:
      train:
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_0.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_1.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_2.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_3.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_6.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_7.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_8.npy
      - cc/defaults/annotations/train_vinvl_bookcorpus_retrieved_sorted_all_9.npy
      # - cc/defaults/annotations/val_vinvl_itm.npy
      val:
      - cc/defaults/annotations/val_vinvl_itm.npy
      test:
      - cc/defaults/annotations/val_vinvl_itm.npy
    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 60
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.9


optimizer:
  type: adam_w
  params:
    lr: 6e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 13000
    num_training_steps: 130000

training:
  batch_size: 480
  lr_scheduler: true
  max_updates: 130000
  find_unused_parameters: true
  tensorboard: true
  clip_gradients: true
  max_grad_l2_norm: 5.0
  epoch_aware: true

evaluation:
  metrics:
  - accuracy

# multitasking:
#   enabled: true
#   type: round_robin
