# includes:
# - ./defaults.yaml

model_config:
  visual_bert:
    visual_target: null
    task_matched: false
    task_visn: true
    use_image_position_embedding: true
    itm_filtering: false
    itm_filtering_start_epoch: 2
dataset_config:
  masked_conceptual_captions_image:
    data_dir: ${env.data_dir}/datasets
    return_features_info: true
    false_caption: false
    two_sentence: false
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
    features:
        train:
        - cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_4.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_5.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_10.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_11.lmdb
        # train:
        # - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        val:
        - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        test:
        - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
    annotations:
      train:
      - cc/defaults/annotations/train_vinvl_bc_retrieved_0.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_1.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_2.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_3.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_4.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_5.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_6.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_7.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_8.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_9.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_10.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_11.npy
      # train:
      # - cc/defaults/annotations/val_vinvl_itm_fixed.npy
      val:
      - cc/defaults/annotations/val_vinvl_itm_fixed.npy
      test:
      - cc/defaults/annotations/val_vinvl_itm_fixed.npy

    processors:
      masked_token_processor:
        type: masked_token_image
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 60
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.9
  masked_conceptual_captions_text:
    data_dir: ${env.data_dir}/datasets
    return_features_info: true
    false_caption: false
    two_sentence: false
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
    features:
        train:
        # - cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_4.lmdb
        # - cc/defaults/features/lmdbs/cc_vinvl_train_5.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_10.lmdb
        - cc/defaults/features/lmdbs/cc_vinvl_train_11.lmdb
        # train:
        # - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        val:
        - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
        test:
        - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
    annotations:
      train:
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_0.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_1.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_2.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_3.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_4.npy
      # - cc/defaults/annotations/train_vinvl_bc_retrieved_5.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_6.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_7.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_8.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_9.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_10.npy
      - cc/defaults/annotations/train_vinvl_bc_retrieved_11.npy
      # train:
      # - cc/defaults/annotations/val_vinvl_itm_fixed.npy
      val:
      - cc/defaults/annotations/val_vinvl_itm_fixed.npy
      test:
      - cc/defaults/annotations/val_vinvl_itm_fixed.npy

    processors:
      masked_token_processor:
        type: masked_token
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 60          
optimizer:
  type: adam_w
  params:
    lr: 6e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 13000
    num_training_steps: 130000

training:
  #batch_size:480
  batch_size: 120
  lr_scheduler: true
  max_updates: 130000
  find_unused_parameters: true
  clip_gradients: true
  max_grad_l2_norm: 5.0
  tensorboard: true
  epoch_aware: false
  checkpoint_interval: 5000
  evaluation_interval: 5000
  num_workers: 2