dataset_config:
  masked_conceptual_captions_image:
    data_dir: ${env.data_dir}/datasets
    return_features_info: true
    false_caption: false
    two_sentence: false
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
    features:
      train:
      - cc/defaults/features/lmdbs/cc_vinvl_train_0.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_1.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_2.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_3.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_6.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_7.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_8.lmdb
      - cc/defaults/features/lmdbs/cc_vinvl_train_9.lmdb
      # train:
      # - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      val:
      - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
      test:
      - cc/defaults/features/lmdbs/cc_vinvl_val.lmdb
    annotations:
      train:
      - cc/defaults/annotations/train_vinvl_0.npy
      - cc/defaults/annotations/train_vinvl_1.npy
      - cc/defaults/annotations/train_vinvl_2.npy
      - cc/defaults/annotations/train_vinvl_3.npy
      - cc/defaults/annotations/train_vinvl_6.npy
      - cc/defaults/annotations/train_vinvl_7.npy
      - cc/defaults/annotations/train_vinvl_8.npy
      - cc/defaults/annotations/train_vinvl_9.npy
      # train:
      # - cc/defaults/annotations/val_vinvl.npy
      val:
      - cc/defaults/annotations/val_vinvl.npy
      test:
      - cc/defaults/annotations/val_vinvl.npy

    processors:
      masked_token_processor:
        type: masked_token_image
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0.15
          max_seq_length: 60
      masked_region_processor:
        type: masked_region
        params:
          mask_probability: 0.15
          mask_region_probability: 0.9