includes:
- ./vinvl_image_data_config.yaml
- ./vinvl_text_data_config.yaml

model_config:
  visual_bert:
    visual_target: null
    task_visn: true
    use_image_position_embedding: true

optimizer:
  type: adam_w
  params:
    lr: 6e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 6500
    num_training_steps: 65000

training:
  #batch_size:480
  batch_size: 240
  lr_scheduler: true
  max_updates: 65000
  find_unused_parameters: true
  clip_gradients: true
  max_grad_l2_norm: 5.0

# multitasking:
#   enabled: true
#   type: round_robin
