model_config:
  visual_bert:
    use_image_position_embedding: true
    hidden_size: 768
    hidden_dropout_prob: 0.1
    training_head_type: nlvr2
    num_labels: 2
    losses:
    - type: cross_entropy

dataset_config:
  nlvr2:
      depth_first: false
      fast_read: false
      use_images: false
      use_features: true
      features:
          train:
          - /home/zmykevin/fb_intern/data/mmf_data/datasets/nlvr2/defaults/features/train_vinvl.lmdb
          val:
          - /home/zmykevin/fb_intern/data/mmf_data/datasets/nlvr2/defaults/features/dev_vinvl.lmdb
          test:
          - /home/zmykevin/fb_intern/data/mmf_data/datasets/nlvr2/defaults/features/test_vinvl.lmdb
      annotations:
          train:
          - /home/zmykevin/fb_intern/data/mmf_data/datasets/nlvr2/defaults/annotations/train.jsonl
          val:
          - /home/zmykevin/fb_intern/data/mmf_data/datasets/nlvr2/defaults/annotations/dev.jsonl
          test:
          - /home/zmykevin/fb_intern/data/mmf_data/datasets/nlvr2/defaults/annotations/test1.jsonl
      max_features: 100
      processors:
        text_processor:
          type: bert_tokenizer
          params:
            tokenizer_config:
              type: bert-base-uncased
              params:
                do_lower_case: true
            mask_probability: 0
            max_seq_length: 128
        bbox_processor:
          type: bbox
          params:
            max_length: 50
        transformer_bbox_processor:
          type: transformer_bbox
          params:
            bbox_key: bbox
            image_width_key: image_width
            image_height_key: image_height
            max_length: 50
      return_features_info: true
optimizer:
  type: adam_w
  params:
    lr: 3e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 1400
    num_training_steps: 14000

evaluation:
  metrics:
  - accuracy

training:
  #batch_size: 480
  batch_size: 60
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 14000
  find_unused_parameters: true
  early_stop:
    criteria: nlvr2/accuracy
    minimize: false

checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
