includes:
- configs/models/mmbt/classification.yaml
- configs/models/mmbt/with_features.yaml

- configs/models/unimodal/text.yaml
- configs/models/unimodal/bert.yaml
# Please see fbcode/faim/mmf/mmf/datasets/fb/builders/hive/builder.py
# for details on configuration
dataset_config:
  hive:
    constructor:
      namespace: si
      table: dim_ci_img_url_05232020_valid_new_with_val
      partitions: null
    set_name_key: set_name
    set_name_mapping:
      train: train
      val: val
      test: test
    schema:
    - post_id
    - label
    - xray_bool
    - body_text
    - title_text
    - ocr_text
    - user_text
    filters: []
    processors:
      batch_processor:
        type: multiclass_features_with_text
        params:
          feature_key: xray_bool
          text_keys:
          - ocr_text
          - body_text
          - title_text
          label_key: label
          id_key: post_id
          processors:
            text_processor:
              type: multi_sentence_bert_tokenizer
              params:
                tokenizer_config:
                  type: bert-base-uncased
                  params:
                    do_lower_case: true
                mask_probability: 0
                max_seq_length: 128
                fusion: concat
            feature_processor:
              type: xray_hash
              params: {}
            label_processor:
              type: multi_class_from_file
              params:
                vocab_file: /mnt/vol/gfsai-oregon/ai-group/users/asg/data/wpie_violations/classes.txt

model_config:
  mmbt:
    direct_features_input: true
    modal_encoder:
      type: identity
      params: {}
    text_encoder:
      params:
        # 2 segments, ocr, body, title and features
        num_segments: 4
    modal_hidden_size: 256
    num_labels: 56


scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

optimizer:
  type: adam_w
  params:
    lr: 1e-5
    eps: 1e-8

evaluation:
    metrics:
    - micro_ap
    - accuracy

training:
  batch_size: 32
  lr_scheduler: true
  max_updates: 22000
  early_stop:
    criteria: hive/micro_ap
    minimize: false
